"""备注信息

Revision ID: 4d76095376a2
Revises: 
Create Date: 2023-03-05 20:39:50.086362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d76095376a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article_tag_table', schema=None) as batch_op:
        batch_op.drop_constraint('article_tag_table_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tag', ['tag_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article_tag_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('article_tag_table_ibfk_2', 'user', ['tag_id'], ['id'])

    # ### end Alembic commands ###
